app/views/user/__init__.py
from flask import Blueprint


user_blu = Blueprint("user_blu", __name__)

from . import views

app/views/user/views.py
import hashlib
import os
from flask_mail import Mail,Message
import random
import time

from flask import render_template, request, redirect, url_for, jsonify, session, current_app, g

from app import db
from app.models.models import User, Detail, Comment
from app.utils.common.common import login_user_data
from 测试发送email import mail

from . import user_blu


# 注册
@user_blu.route("/reg", methods=["GET", "POST"])
def reg():
    if request.method == "GET":
        session["num1"] = random.randint(0, 9)
        session["num2"] = random.randint(0, 9)
        return render_template("user/reg.html")
    elif request.method == "POST":
        localtime = time.asctime(time.localtime(time.time()))
        create_time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())  # 注册的时间
        email = request.form.get("email")
        username = request.form.get("username")
        password = request.form.get("pass")
        repass = request.form.get("repass")
        vercode = request.form.get("vercode")
        ss = session.get("num1") + session.get("num2")
        print(email, username, password, repass, vercode)
        print(ss, '-----人类验证码')
        # 查询用户注册的邮箱是否存在
        user = db.session.query(User).filter(User.email == email).first()
        if user:
            return "用户名存在"

        # 数据库添加
        if int(vercode) == int(ss):
            user = User()
            if user:
                # 用户注册成功
                user.email = email
                user.user_name = username
                user.password_hash = password
                user.create_time = create_time
                db.session.add(user)
                db.session.commit()
                # 2 重定向到index
                return redirect("/login")

            return "Aa"
        return "验证码错误"


# 登录
@user_blu.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        session["number1"] = random.randint(0, 9)
        session["number2"] = random.randint(0, 9)
        return render_template("user/login.html")

    elif request.method == "POST":
        # 1 获取数据
        email = request.form.get("email")  # 邮箱
        password = request.form.get("password")
        vercode = request.form.get("vercode")
        ss = session.get("number1") + session.get("number2")

        print(email, password, vercode)

        if int(vercode) == int(ss):
            # 2 数据库查询
            user_info = db.session.query(User).filter(User.email == email, User.password_hash == password).first()

            if user_info:
                # 如果验证用户登录成功

                # 1 通过session存储用户的信息
                session["user_id"] = user_info.id

                # 2 使用重定向到index主义
                return redirect("/index")

            # 如果用户未登录成功再次跳转到登录页面
            return redirect("/login")


# 退出
@user_blu.route("/logout")
# @login_user_data
def logout():
    # 退出清除session 标记
    session.clear()
    print("退出清除session成功")

    # 2 返回主页
    return redirect("/index")


# 忘记密码
@user_blu.route("/forget", methods=["POST", "GET"])
def forget():
    if request.method == "GET":
        session["number1"] = random.randint(0, 9)
        session["number2"] = random.randint(0, 9)
        return render_template("user/forget.html")
    elif request.method == "POST":
        # 1 获取参数
        email = request.form.get("email")
        vercode = request.form.get("vercode")
        ss = session.get("number1") + session.get("number2")
        print(email)
        if int(vercode) == int(ss):
            # 数据库查询
            user_email = db.session.query(User).filter(User.email == email).first()
            print(user_email, "查询用户的email是否有对应")
            if user_email:
                # 如果查询到了用户输入的邮箱与查询出来的邮箱成立就执行下面的事情

                # 1 通过session存储email
                session["user_email"] = user_email.email  # 邮箱

                email_user = session.get("user_email")
                print(email_user, "email_user")

                # 2 邮箱验证
                # 通过hashlib相关功能得到一个随机值，这个 随机值出现可能性的概率几乎为0
                mail_hash = hashlib.md5()
                mail_hash.update(str(time.time()).encode("utf-8"))
                email_hash_value = mail_hash.hexdigest()

                # 制作一个url，用来发送到电子邮箱中，从而才能让用户点击
                # http://localhost:5000/verify_email?email_hash=aksdjflasjdflkjaskldfjlasdjflksjdf
                verify_email_url = request.host_url + "forget3?user_email=" + email_user

                # sender发信人  recipients收信人
                msg = Message('欢迎来到Fly社区，请验证', sender='13030119817@163.com', recipients=[email])
                msg.body = '你好'
                msg.html = "你好，点击<a href=%s >修改密码</a>, 如有问题请联系Fly社区管理员" % verify_email_url
                mail.send(msg)

                # 返回
                return "邮箱验证发送成功点击<a href=https://mail.163.com/>登录</a>邮箱验证"

            else:
                return "邮箱不存在"

        return "验证码错误"


@user_blu.route("/forget3", methods=["POST", "GET"])
def forget3():
    """忘记密码"""
    if request.method == "GET":

        return render_template("user/forgetPwd3.html")

    elif request.method == "POST":
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        user_email = session.get("user_email")  # 用户输入的忘记密码的邮箱
        print(password1, password2, user_email)

        # 查询出当前改密码的用户是否与数据库相同
        new_user = db.session.query(User).filter(User.email == user_email).first()
        # 判断
        if new_user:
            if not (password1 and password2):
                return "缺少参数 点击<a href=/forget3>返回</a>"
            if password1 != password2:
                return "两次密码不一致 点击<a href=/forget3>返回</a>"
            if password1 == password2:
                # print(new_user.password)
                new_user.password_hash = password1
                # 提交
                db.session.commit()

            return redirect(url_for(".forget_pwd4"))
        return "不能重新修改密码谢谢 点击<a href=/login>返回</a>"


@user_blu.route("/forget_pwd4")
def forget_pwd4():
    session.clear()  # 清除session 用户只能在验证通过后修改一次密码
    return render_template("user/forgetPwd4.html")


# 主页
@user_blu.route("/home")
@login_user_data
def home():
    try:
        ss = db.session.query(Detail).filter(Detail.user_id == g.user.id).first()
        # print(ss, '-----发布帖子的id', g.user.id)
        reply_s = db.session.query(Comment).filter(Comment.detail_id == ss.id).all()
        # print(len(reply_s), '--------回帖人数')
        issue = db.session.query(Detail).filter(Detail.user_id == g.user.id).all()
        # print(issue, '----当前id所发布的所用帖子')
        user_answer = db.session.query(Comment).filter(Comment.user_id == g.user.id).all()
        print(user_answer, '-------------当前用户回复表的id')
        return render_template("user/home.html", user=g.user, reply_s=len(reply_s), issue=issue, user_answer=user_answer)
    except Exception as re:
        # return render_template("user/home.html", user=g.user, user_answer=user_answer)
        return render_template("user/home.html", user=g.user)


# 用户中心
@user_blu.route("/user_index")
@login_user_data
def user_index():
    user_id = session.get("user_id")
    print(user_id)
    detail = db.session.query(Detail).filter(Detail.user_id == user_id).all()
    num = len(detail)
    print(detail)
    return render_template("user/index.html", detail=detail, num=num, user=g.user)


# 基本设置
@user_blu.route("/set", methods=["GET", "POST"])
def set():
    # 1.获取用户id
    user_id = session.get("user_id")
    # 2.查询数据库
    user = db.session.query(User).filter(User.id == user_id).first()
    if request.method == "GET":
        return render_template("user/set.html", user=user)
    elif request.method == "POST":
        # 获取信息
        email = request.form.get("email")
        username = request.form.get("username")
        sex = request.form.get("sex")
        city = request.form.get("city")
        sign = request.form.get("sign")
        nowpass = request.form.get("nowpass")
        passs = request.form.get("pass")
        repass = request.form.get("repass")
        if email:
            # 修改用户信息
            user.email = email
            user.user_name = username
            user.gender = sex
            user.city = city
            user.signature = sign

        if user.password_hash == nowpass:
            if passs == repass:
                user.password_hash = passs
        # 提交信息
        db.session.commit()
        # 修改成功跳转
        return redirect("/home")


@user_blu.route("/upload/", methods=["POST"])
@user_blu.route("/user/upload/", methods=["POST"])
def upload():
    # 获取登录用户的id
    user_id = session.get("user_id")
    # # 从数据库中查询这个用户
    user = db.session.query(User).filter(User.id == user_id).first()
    # return render_template("user/set.html", user=user)
    # 1.获取信息
    binary = request.files.get("binary")
    print(binary)
    # return "1234"
    file = request.files.get("file")
    print(file)
    # 2.判断
    if file:
        file_hash = hashlib.md5()
        file_hash.update(file.filename.encode("utf-8"))
        file_name = file_hash.hexdigest() + file.filename[file.filename.rfind("."):]
        local_file_path = os.path.join("/static/upload/images", file_name)

        file_path = os.path.join(current_app.root_path, "static/upload/images", file_name)

        file.save(file_path)

        user.avatar_url = local_file_path
        db.session.commit()
        return "成功"
    else:
        return "出错了"


# 我的消息
@user_blu.route("/message")
def message():
    return render_template("user/message.html")


# 邮箱激活
@user_blu.route("/activate")
def activate():
    return render_template("user/activate.html")

app/templates/user/activate.html
 
 
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>激活邮箱</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="keywords" content="fly,layui,前端社区">
  <meta name="description" content="Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力">
  <link rel="stylesheet" href="../../static/layui/css/layui.css">
  <link rel="stylesheet" href="../../static/css/global.css">
</head>
<body>

<div class="fly-header layui-bg-black">
  <div class="layui-container">
    <a class="fly-logo" href="/">
      <img src="../../static/images/logo.png" alt="layui">
    </a>
    <ul class="layui-nav fly-nav layui-hide-xs">
      <li class="layui-nav-item layui-this">
        <a href="/"><i class="iconfont icon-jiaoliu"></i>交流</a>
      </li>
      <li class="layui-nav-item">
        <a href="../case/case.html"><i class="iconfont icon-iconmingxinganli"></i>案例</a>
      </li>
      <li class="layui-nav-item">
        <a href="http://www.layui.com/" target="_blank"><i class="iconfont icon-ui"></i>框架</a>
      </li>
    </ul>
    
    <ul class="layui-nav fly-nav-user">
      <!-- 登入后的状态 -->
      <li class="layui-nav-item">
        <a class="fly-nav-avatar" href="javascript:;">
          <cite class="layui-hide-xs">贤心</cite>
          <i class="iconfont icon-renzheng layui-hide-xs" title="认证信息：layui 作者"></i>
          <i class="layui-badge fly-badge-vip layui-hide-xs">VIP3</i>
          <img src="https://tva1.sinaimg.cn/crop.0.0.118.118.180/5db11ff4gw1e77d3nqrv8j203b03cweg.jpg">
        </a>
        <dl class="layui-nav-child">
          <dd><a href="../user/set.html"><i class="layui-icon">&#xe620;</i>基本设置</a></dd>
          <dd><a href="../user/message.html"><i class="iconfont icon-tongzhi" style="top: 4px;"></i>我的消息</a></dd>
          <dd><a href="../user/home.html"><i class="layui-icon" style="margin-left: 2px; font-size: 22px;">&#xe68e;</i>我的主页</a></dd>
          <hr style="margin: 5px 0;">
          <dd><a href="" style="text-align: center;">退出</a></dd>
        </dl>
      </li>
    </ul>
  </div>
</div>

<div class="layui-container fly-marginTop fly-user-main">
  <ul class="layui-nav layui-nav-tree layui-inline" lay-filter="user">
    <li class="layui-nav-item">
      <a href="home">
        <i class="layui-icon">&#xe609;</i>
        我的主页
      </a>
    </li>
    <li class="layui-nav-item layui-this">
      <a href="index">
        <i class="layui-icon">&#xe612;</i>
        用户中心
      </a>
    </li>
    <li class="layui-nav-item">
      <a href="set">
        <i class="layui-icon">&#xe620;</i>
        基本设置
      </a>
    </li>
    <li class="layui-nav-item">
      <a href="message">
        <i class="layui-icon">&#xe611;</i>
        我的消息
      </a>
    </li>
  </ul>

  <div class="site-tree-mobile layui-hide">
    <i class="layui-icon">&#xe602;</i>
  </div>
  <div class="site-mobile-shade"></div>
  
  <div class="site-tree-mobile layui-hide">
    <i class="layui-icon">&#xe602;</i>
  </div>
  <div class="site-mobile-shade"></div>
  
  
  <div class="fly-panel fly-panel-user" pad20>
    <div class="layui-tab layui-tab-brief" lay-filter="user">
      <ul class="layui-tab-title">
        <li class="layui-this">
          激活邮箱
        </li>
      </ul>
      <div class="layui-tab-content" id="LAY_ucm" style="padding: 20px 0;">
        <ul class="layui-form">
          <li class="layui-form-li">
            <label for="activate">您的邮箱：</label>
            <span class="layui-form-text">xx@xx.com
              <!-- <em style="color:#999;">（已成功激活）</em> -->
              <em style="color:#c00;">（尚未激活）</em>
            </span>
          </li>
          <li class="layui-form-li" style="margin-top: 20px; line-height: 26px;">
            <div>
              1. 如果您未收到邮件，或激活链接失效，您可以
              <a class="layui-form-a" style="color:#4f99cf;" id="LAY-activate" href="javascript:;" email="">重新发送邮件</a>，或者
              <a class="layui-form-a" style="color:#4f99cf;" href="set">更换邮箱</a>；
            </div>
            <div>
              2. 如果您始终没有收到 Fly 发送的邮件，请注意查看您邮箱中的垃圾邮件；
            </div>
            <div>
              3. 如果你实在无法激活邮件，您还可以联系：admin@xx.com
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  
</div>

<div class="fly-footer">
  <p><a href="http://fly.layui.com/" target="_blank">Fly社区</a> 2017 &copy; <a href="http://www.layui.com/" target="_blank">layui.com 出品</a></p>
  <p>
    <a href="http://fly.layui.com/jie/3147/" target="_blank">付费计划</a>
    <a href="http://www.layui.com/template/fly/" target="_blank">获取Fly社区模版</a>
    <a href="http://fly.layui.com/jie/2461/" target="_blank">微信公众号</a>
  </p>
</div>

<script src="../../static/layui/layui.js"></script>
<script>
layui.cache.page = 'user';
layui.cache.user = {
  username: '游客'
  ,uid: -1
  ,avatar: '../../static/images/avatar/00.jpg'
  ,experience: 83
  ,sex: '男'
};
layui.config({
  version: "3.0.0"
  ,base: '../../static/mods/'
}).extend({
  fly: 'index'
}).use('fly');
</script>

</body>
</html>

app/templates/user/home.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>用户主页</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="keywords" content="fly,layui,前端社区">
  <meta name="description" content="Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力">
  <link rel="stylesheet" href="../../static/layui/css/layui.css">
  <link rel="stylesheet" href="../../static/css/global.css">
</head>
<body style="margin-top: 65px;">

<div class="fly-header layui-bg-black">
  <div class="layui-container">
    <a class="fly-logo" href="/">
      <img src="../../static/images/logo.png" alt="layui">
    </a>
    <ul class="layui-nav fly-nav layui-hide-xs">
      <li class="layui-nav-item layui-this">
        <a href="/"><i class="iconfont icon-jiaoliu"></i>交流</a>
      </li>
      <li class="layui-nav-item">
        <a href="../case/case.html"><i class="iconfont icon-iconmingxinganli"></i>案例</a>
      </li>
      <li class="layui-nav-item">
        <a href="http://www.layui.com/" target="_blank"><i class="iconfont icon-ui"></i>框架</a>
      </li>
    </ul>
    
    {% if user %}
        <ul class="layui-nav fly-nav-user">
      <!-- 登入后的状态 -->
      <li class="layui-nav-item">
        <a class="fly-nav-avatar" href="javascript:;">
          <cite class="layui-hide-xs">{{ user.user_name }}</cite>
          <i class="iconfont icon-renzheng layui-hide-xs" title="认证信息：layui 作者"></i>
            {% if user.id == 2 %}
          <i class="layui-badge fly-badge-vip layui-hide-xs">VIP3</i>
            {% endif %}
           {% if user.avatar_url %}
            <img src="{{ user.avatar_url }}">
            {% else %}
                <img src="../../static/images/avatar/5.jpg">
            {% endif %}
        </a>
        <dl class="layui-nav-child">
          <dd><a href="{{ url_for("user_blu.set") }}"><i class="layui-icon">&#xe620;</i>基本设置</a></dd>
          <dd><a href="{{ url_for("user_blu.message") }}"><i class="iconfont icon-tongzhi" style="top: 4px;"></i>我的消息</a></dd>
          <dd><a href="{{ url_for("user_blu.home") }}"><i class="layui-icon" style="margin-left: 2px; font-size: 22px;">&#xe68e;</i>我的主页</a></dd>
          <hr style="margin: 5px 0;">
          <dd><a href="{{ url_for("user_blu.logout") }}" style="text-align: center;">退出</a></dd>
        </dl>
      </li>
    </ul>

    {% endif %}
  </div>
</div>

<div class="fly-home fly-panel" style="background-image: url();">
{% if user.avatar_url %}
     <img src="{{ user.avatar_url }}" alt="贤心">
{% else %}
    <img src="../../static/images/avatar/5.jpg">

{% endif %}

  <i class="iconfont icon-renzheng" title="Fly社区认证"></i>
  <h1>
    {{ user.user_name }}
    <i class="iconfont icon-nan"></i>
    <!-- <i class="iconfont icon-nv"></i>  -->
      {% if user.id == 2 %}
    <i class="layui-badge fly-badge-vip">VIP3</i>
      {% endif %}
    <!--
    <span style="color:#c00;">（管理员）</span>
    <span style="color:#5FB878;">（社区之光）</span>
    <span>（该号已被封）</span>
    -->
  </h1>

  <p style="padding: 10px 0; color: #5FB878;">认证信息:管理员</p>

  <p class="fly-home-info">
    <i class="iconfont icon-kiss" title="飞吻"></i><span style="color: #FF7200;">66666 飞吻</span>
    <i class="iconfont icon-shijian"></i><span>{{ user.create_time }}</span>
    <i class="iconfont icon-chengshi"></i><span>来自{{ user.city }}</span>
  </p>
    {% if user.signature %}
    <p class="fly-home-sign">（{{ user.signature }}）</p>
    {% else %}
    <p class="fly-home-sign">（这个用户很懒，什么也没有留下）</p>
    {% endif %}


</div>

<div class="layui-container">
  <div class="layui-row layui-col-space15">
    <div class="layui-col-md6 fly-home-jie">
      <div class="fly-panel">
        <h3 class="fly-panel-title">{{ user.user_name }}的帖子</h3>
        <ul class="jie-row">
            {% for x in issue %}
                <li>
                    <a href="" class="jie-title">{{ x.title }}</a>
                    <i>{{ x.create_time }}</i>
                    <em class="layui-hide-xs">{{ reply_s }}回复</em>
                </li>
            {% endfor %}

          <!-- <div class="fly-none" style="min-height: 50px; padding:30px 0; height:auto;"><i style="font-size:14px;">没有发表任何求解</i></div> -->
        </ul>
      </div>
    </div>
    
    <div class="layui-col-md6 fly-home-da">
      <div class="fly-panel">
        <h3 class="fly-panel-title">{{ user.user_name }}的回答</h3>

        <ul class="home-jieda">
            {% for i in user_answer %}
                <li>

                    <a href="/detail/{{ i.detail_id }}" class="jie-title">{{ i.content }}</a>
                    <i>{{ i.contet }}</i>

                    <em class="layui-hide-xs"></em>
                </li>
            {% endfor %}

        
          <!-- <div class="fly-none" style="min-height: 50px; padding:30px 0; height:auto;"><span>没有回答任何问题</span></div> -->
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="fly-footer">
  <p><a href="http://fly.layui.com/" target="_blank">Fly社区</a> 2017 &copy; <a href="http://www.layui.com/" target="_blank">layui.com 出品</a></p>
  <p>
    <a href="http://fly.layui.com/jie/3147/" target="_blank">付费计划</a>
    <a href="http://www.layui.com/template/fly/" target="_blank">获取Fly社区模版</a>
    <a href="http://fly.layui.com/jie/2461/" target="_blank">微信公众号</a>
  </p>
</div>

<script src="../../static/layui/layui.js"></script>
<script>
layui.cache.page = 'user';
layui.cache.user = {
  username: '游客'
  ,uid: -1
  ,avatar: '../../static/images/avatar/00.jpg'
  ,experience: 83
  ,sex: '男'
};
layui.config({
  version: "3.0.0"
  ,base: '../../static/mods/'
}).extend({
  fly: 'index'
}).use('fly');
</script>

</body>
</html>

app/templates/user/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>用户中心</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="keywords" content="fly,layui,前端社区">
  <meta name="description" content="Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力">
  <link rel="stylesheet" href="../../static/layui/css/layui.css">
  <link rel="stylesheet" href="../../static/css/global.css">
</head>
<body>

<div class="fly-header layui-bg-black">
  <div class="layui-container">
    <a class="fly-logo" href="/">
      <img src="../../static/images/logo.png" alt="layui">
    </a>
    <ul class="layui-nav fly-nav layui-hide-xs">
      <li class="layui-nav-item layui-this">
        <a href="/"><i class="iconfont icon-jiaoliu"></i>交流</a>
      </li>
      <li class="layui-nav-item">
        <a href="../case/case.html"><i class="iconfont icon-iconmingxinganli"></i>案例</a>
      </li>
      <li class="layui-nav-item">
        <a href="http://www.layui.com/" target="_blank"><i class="iconfont icon-ui"></i>框架</a>
      </li>
    </ul>
   {% if user %}
        <ul class="layui-nav fly-nav-user">
      <!-- 登入后的状态 -->
      <li class="layui-nav-item">
        <a class="fly-nav-avatar" href="javascript:;">
          <cite class="layui-hide-xs">{{ user.user_name }}</cite>
          <i class="iconfont icon-renzheng layui-hide-xs" title="认证信息：layui 作者"></i>
            {% if user.id == 2 %}
          <i class="layui-badge fly-badge-vip layui-hide-xs">VIP3</i>
            {% endif %}
           {% if user.avatar_url %}
            <img src="{{ user.avatar_url }}">
            {% else %}
                <img src="../../static/images/avatar/5.jpg">
            {% endif %}
        </a>
        <dl class="layui-nav-child">
          <dd><a href="{{ url_for("user_blu.set") }}"><i class="layui-icon">&#xe620;</i>基本设置</a></dd>
          <dd><a href="{{ url_for("user_blu.message") }}"><i class="iconfont icon-tongzhi" style="top: 4px;"></i>我的消息</a></dd>
          <dd><a href="{{ url_for("user_blu.home") }}"><i class="layui-icon" style="margin-left: 2px; font-size: 22px;">&#xe68e;</i>我的主页</a></dd>
          <hr style="margin: 5px 0;">
          <dd><a href="{{ url_for(".logout") }}" style="text-align: center;">退出</a></dd>
        </dl>
      </li>
    </ul>

    {% endif %}
  </div>
</div>

<div class="layui-container fly-marginTop fly-user-main">
  <ul class="layui-nav layui-nav-tree layui-inline" lay-filter="user">
    <li class="layui-nav-item">
      <a href="home">
        <i class="layui-icon">&#xe609;</i>
        我的主页
      </a>
    </li>
    <li class="layui-nav-item layui-this">
      <a href="#">
        <i class="layui-icon">&#xe612;</i>
        用户中心
      </a>
    </li>
    <li class="layui-nav-item">
      <a href="set">
        <i class="layui-icon">&#xe620;</i>
        基本设置
      </a>
    </li>

  </ul>

  <div class="site-tree-mobile layui-hide">
    <i class="layui-icon">&#xe602;</i>
  </div>
  <div class="site-mobile-shade"></div>
  
  <div class="site-tree-mobile layui-hide">
    <i class="layui-icon">&#xe602;</i>
  </div>
  <div class="site-mobile-shade"></div>
  
  
  <div class="fly-panel fly-panel-user" pad20>
    <!--
    <div class="fly-msg" style="margin-top: 15px;">
      您的邮箱尚未验证，这比较影响您的帐号安全，<a href="activate.templates">立即去激活？</a>
    </div>
    -->
    <div class="layui-tab layui-tab-brief" lay-filter="user">
      <ul class="layui-tab-title" id="LAY_mine">
        <li data-type="mine-jie" lay-id="index" class="layui-this">我发的帖（<span>{{ num }}</span>）</li>
        <li data-type="collection" data-url="/collection/find/" lay-id="collection">我收藏的帖（<span>16</span>）</li>
      </ul>
      <div class="layui-tab-content" style="padding: 20px 0;">
        <div class="layui-tab-item layui-show">
        {% for x in detail %}
          <ul class="mine-view jie-row">
            <li>
              <a class="jie-title" href="../detail/{{ x.id }}" target="_blank">{{ x.title }}</a>
              <i>{{ x.create_time }}</i>
              <a class="mine-edit" href="/jie/edit/{{ x.id }}">编辑</a>
              <em>661阅/10答</em>
            </li>
          </ul>
        {% endfor %}
          <div id="LAY_page"></div>
        </div>
        <div class="layui-tab-item">
          <ul class="mine-view jie-row">
            <li>
              <a class="jie-title" href="../jie/detail.html" target="_blank">基于 layui 的极简社区页面模版</a>
              <i>收藏于23小时前</i>  </li>
          </ul>
          <div id="LAY_page1"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="fly-footer">
  <p><a href="http://fly.layui.com/" target="_blank">Fly社区</a> 2017 &copy; <a href="http://www.layui.com/" target="_blank">layui.com 出品</a></p>
  <p>
    <a href="http://fly.layui.com/jie/3147/" target="_blank">付费计划</a>
    <a href="http://www.layui.com/template/fly/" target="_blank">获取Fly社区模版</a>
    <a href="http://fly.layui.com/jie/2461/" target="_blank">微信公众号</a>
  </p>
</div>

<script src="../../static/layui/layui.js"></script>
<script>
layui.cache.page = 'user';
layui.cache.user = {
  username: '游客'
  ,uid: -1
  ,avatar: '../../static/images/avatar/00.jpg'
  ,experience: 83
  ,sex: '男'
};
layui.config({
  version: "3.0.0"
  ,base: '../../static/mods/'
}).extend({
  fly: 'index'
}).use('fly');
</script>

</body>
</html>